apiVersion: networking.openshift.io/v1beta1
kind: BGPRouting
metadata:
  name: bgprouting-{{.Iteration}}
spec:
  network:
    name: cudn-{{.Iteration}}
    subnets:
    {{- range $i, $v := until $.cidrs_per_cudn }}
      {{- $cidrIndex := add (mul $.Iteration $.cidrs_per_cudn) $i }}
      {{- $firstOctet := add (div $cidrIndex 255) 40 }}
      {{- $secondOctet := mod $cidrIndex 255 }}
      - {{ print $firstOctet "." $secondOctet ".0.0/16" }}
    {{- end }}
